version: "3.8"

services:
  mongodb:
    image : mongo:latest
    environment:
     - PUID=1000
     - PGID=1000
    volumes:
      - /alpha-euro-stroy:/data/db
    ports:
      - "27017:27017"
volumes:
  alpha-euro-stroy:
